### PR TITLE
Fix artifacts directory in github actions

### PR DESCRIPTION
**Pull request by cschindlbeck**

### CODE REVIEW

**Comment by marip8** [comment]
Is this not the solution to the build error? I was trying to figure this out but didn't have more time to figure it out yet

**Comment by marip8** [comment]
This may actually solve the issue. This job only runs when tags are created, hence my creation of 4.0.1-5 to test the job. I think you could test by opening this PR against the master branch on your own fork, merging it, then pushing a new tag to the repo and checking the job status. I should have done it this way for the previous few patches

**Comment by cschindlbeck** [comment]
Ah, just saw the on tags, i pushed a test tag here: https://github.com/cschindlbeck/ros_industrial_cmake_boilerplate/actions/runs/4346943449/jobs/7593640605

It helped to find that i forgot to add the -p option but it appears to work fine

**Comment by marip8** [comment]
Looks good to me. Thanks for figuring this out and testing

**Review by marip8 — APPROVED** [review]

**Pull request merged**
