### PR TITLE
Move contributing and license file to the repo level directory

### PR DESCRIPTION
**Pull request by Levi-Armstrong**

### CODE REVIEW

**Comment by Levi-Armstrong** [comment]
@gavanderhoorn Like this?

Every time I go through the release process should it be creating a new PR or updating the existing PR?

**Comment by Levi-Armstrong** [comment]
@gavanderhoorn Is this the location they should be?

**Review by gavanderhoorn — APPROVED** [review]
Makes sense to me to have them in the root.

**Comment by Levi-Armstrong** [comment]
Thank you.

**Pull request merged**
