### PR TITLE
Add license files and update documentation

### PR DESCRIPTION
**Pull request by Levi-Armstrong**

### CODE REVIEW

**Comment by Levi-Armstrong** [comment]
@gavanderhoorn ros/rodistro maintainers asked for license files to be added. Do you see any issues how I have added them?

**Comment by gavanderhoorn** [comment]
Pff. It's one thing to want to enhance quality of your own packages, but it's another to be anal about it when dealing with other people's work.

In any case: yes, I believe this would be fine.

You've included the license files, did you not?

**Comment by Levi-Armstrong** [comment]
> Pff. It's one thing to want to enhance quality of your own packages, but it's another to be anal about it when dealing with other people's work.

I feel the same way.

> You've included the license files, did you not?

Yea, I just was not sure about when having two licenses used in a repository. This seems more confusing because it does not provide any indication to which file it applies to.

**Comment by gavanderhoorn** [comment]
> Yea, I just was not sure about when having two licenses used in a repository. This seems more confusing because it does not provide any indication to which file it applies to.

Oh, ok.

You typically include the license header / summary at the top of the file it applies to.

**Comment by Levi-Armstrong** [comment]
> You typically include the license header / summary at the top of the file it applies to.

Yea, that is usually the only thing I do. Should I state anywhere what the preferred license is for contributors?

**Comment by gavanderhoorn** [comment]
Yes, that would be good.

If you create a `CONTRIBUTING.md`, Github will show that to anyone who submits a PR.

See [ros2/examples/CONTRIBUTING.md](https://github.com/ros2/examples/blob/847596756e9a0be95b2c42b803002ec6e8f0893f/CONTRIBUTING.md) fi.

**Comment by Levi-Armstrong** [comment]
> Yes, that would be good.
> 
> If you create a `CONTRIBUTING.md`, Github will show that to anyone who submits a PR.
> 
> See [ros2/examples/CONTRIBUTING.md](https://github.com/ros2/examples/blob/847596756e9a0be95b2c42b803002ec6e8f0893f/CONTRIBUTING.md) fi.

Should I add [this](https://github.com/probot/dco) to the repository for the DCO, or is there another one I should use?

**Comment by gavanderhoorn** [comment]
> Should I add [this](https://github.com/probot/dco) to the repository for the DCO, or is there another one I should use?

I don't believe we need a DCO.

I only linked to that file for the license clause.

**Comment by Levi-Armstrong** [comment]
@gavanderhoorn How does this look?

**Review by gavanderhoorn — APPROVED** [review]

**Comment by gavanderhoorn** [comment]
Oh, I only now noticed you didn't put the `CONTRIBUTING.md` at the root of the repository.

I'm not sure whether Github will pick up on it where it is now.

Same with the license files actually.

**Comment by Levi-Armstrong** [comment]
see #30

**Pull request merged**
