### PR TITLE
Minor fixes, see commit message for details

### PR DESCRIPTION
**Pull request by Levi-Armstrong**
target_code_coverage did not allow you to use plain visibility because the default was private. This prevents the use of this on any target that is created with plain visibility. The current case found is when using ros gtest marco which creates targets with plain visibility and provides no way to specify the visibility. This was an misunderstanding on my part of cmake because I was not aware if you do not provide PUBLIC, PRIVATE, or INTERFACE that it had its own visibility category.

### CODE REVIEW

**Review by marip8 — APPROVED** [review]
I don't really understand the Windows c++ standard updates, but everything else looks fine to me.

**Comment by Levi-Armstrong** [comment]
Note: this is a breaking change.

**Comment by marip8** [comment]
> Note: this is a breaking change.

It's a minor change though, right? I think this is still backwards compatible with 0.2.x

**Comment by Levi-Armstrong** [comment]
> > Note: this is a breaking change.
> 
> It's a minor change though, right? I think this is still backwards compatible with 0.2.x

Yea it is minor, and is only backwards compatible if you specified the visibility. In tesseract I did not do this and let it use the default so I had to go through and add PRIVATE every where. I have an open PR.

**Pull request merged**
